### ISSUE TITLE
make tab complete and 

### ISSUE THREAD

**Issue by TymekSL** [Mirroray41/Coordinator#2]
Please add tab complete in next version and make the reload message changeable. I mean add this to the translation, I want make this messafe better  and colored

**Comment by TymekSL** [comment]
2. Please color the coordinates (add the placeholder to be colored)

**Comment by Mirroray41** [comment]
> Please add tab complete in next version and make the reload message changeable. I mean add this to the translation, I want make this messafe better and colored

I though about it and I dont know if its a good idea, mainly because youre reading the configs into memory right before the message is sent

**Comment by Mirroray41** [comment]
> 2. Please color the coordinates (add the placeholder to be colored)

youll have to color the bossbar title from its own config using the prefixes you asked about in your previous issue

**Comment by Mirroray41** [comment]
> Please add tab complete in next version and make the reload message changeable. I mean add this to the translation, I want make this messafe better and colored

for the tab complete, ill add it once Ive done the whole command control system

**Comment by Mirroray41** [comment]
Also gotta admit you were right about the need for a discord support server, as around 20 people downloaded 1.2 and no one reported ether one of the two glaring bugs I had in there(fixed in 1.3) so you should see one soon

**Comment by TymekSL** [comment]
> > Please add tab complete in next version and make the reload message changeable. I mean add this to the translation, I want make this messafe better and colored
> 
> I though about it and I dont know if its a good idea, mainly because youre reading the configs into memory right before the message is sent

i dont understand this, why? its just one message xD

**Comment by TymekSL** [comment]
> Also gotta admit you were right about the need for a discord support server, as around 20 people downloaded 1.2 and no one reported ether one of the two glaring bugs I had in there(fixed in 1.3) so you should see one soon

yes, just 2-3 channels for now and one bot no more needed ;D (ticket system for priv problems wil be good too)

**Comment by TymekSL** [comment]
https://prnt.sc/AAYFFOtSTchp 

> > Please add tab complete in next version and make the reload message changeable. I mean add this to the translation, I want make this messafe better and colored
> 
> I though about it and I dont know if its a good idea, mainly because youre reading the configs into memory right before the message is sent

i need only this colored ;(

**Comment by Mirroray41** [comment]
That's done by the location prefix under prefixes in translations.yaml

**Comment by Mirroray41** [comment]
I belive this discussion will be faster on discord, please join the server(link in readme)

**Comment by TymekSL** [comment]
Discriminating people for nationality, Fuck you and your fucked up plugin

**Comment by Mirroray41** [comment]
![obrazek](https://github.com/Mirroray41/Coordinator/assets/87991171/c30e483e-daa9-4950-aea0-04fb8350777c)

...

**Comment by TymekSL** [comment]
> ![obrazek](https://private-user-images.githubusercontent.com/87991171/318689355-c30e483e-daa9-4950-aea0-04fb8350777c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwOTE3MzQsIm5iZiI6MTcxMjA5MTQzNCwicGF0aCI6Ii84Nzk5MTE3MS8zMTg2ODkzNTUtYzMwZTQ4M2UtZGFhOS00OTUwLWFlYTAtMDRmYjgzNTA3NzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDIwNTcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4Yjk3NTIxNjgyNTk3OGU0ZGU3MmE3Y2M1YzU0YTkzYjMxZTFmMzllNDU0Y2EzMTQyNjZiODJmZmM1NWY2NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZSP7oXPL8mCXJRGHoblS-bYQlUg4ytsTrEknBm538ls)
> 
> ...

ugh sorry, I missunderstood this as im from Poland and you won't help me it was weird and at first time didn't marked as exciting but as discriminatic 
sorry again ;<

**Comment by Mirroray41** [comment]
It's fine, we all make mistakes, if you have more ideas/suggestions don't forget to mention them!

**Comment by Mirroray41** [comment]
It's fine, we all make mistakes, if you have more ideas/suggestions don't forget to mention them!

**Comment by Mirroray41** [comment]
Also could you please remove the 1 star raining from spigot, as it's kinda lowering the overall rating?
